<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Bulk Receipts - {{ date('Y-m-d') }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; padding: 10px; }
        .page-break { page-break-after: always; }
        .receipt-box {
            max-width: 700px;
            margin: 0 auto 20px auto;
            border: 2px solid #1a237e;
            border-radius: 10px;
            padding: 15px 20px;
            background: #fff;
            page-break-inside: avoid;
        }
        .receipt-header { text-align: center; border-bottom: 2px solid #1a237e; padding-bottom: 8px; margin-bottom: 10px; }
        .receipt-header .logo { font-size: 16px; font-weight: bold; color: #1a237e; }
        .receipt-header .receipt-no { font-size: 12px; font-weight: bold; color: #c62828; }
        .row { display: flex; justify-content: space-between; padding: 2px 0; border-bottom: 1px dashed #e0e0e0; font-size: 9px; }
        .row:last-child { border-bottom: none; }
        .label { font-weight: bold; color: #555; width: 35%; }
        .value { width: 65%; text-align: right; }
        .section-title { font-weight: bold; color: #1a237e; font-size: 10px; margin: 6px 0 4px 0; border-bottom: 1px solid #1a237e; padding-bottom: 3px; }
        .total-row { background: #e8eaf6; padding: 4px 8px; border-radius: 4px; margin: 4px 0; display: flex; justify-content: space-between; font-size: 10px; }
        .total-row .label { font-weight: bold; color: #1a237e; }
        .total-row .value { font-weight: bold; color: #1a237e; }
        .status-badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 8px; font-weight: bold; }
        .status-paid { background: #c8e6c9; color: #2e7d32; }
        .status-pending { background: #ffcdd2; color: #c62828; }
        .status-partial { background: #ffe0b2; color: #e65100; }
        .footer { text-align: center; font-size: 7px; color: #999; margin-top: 5px; }
        .cover-page {
            text-align: center;
            padding: 80px 20px;
            border: 3px solid #1a237e;
            border-radius: 15px;
            min-height: 500px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .cover-page h1 { font-size: 28px; color: #1a237e; margin-bottom: 10px; }
        .cover-page h2 { font-size: 18px; color: #666; margin-bottom: 30px; }
        .cover-page .details { font-size: 12px; color: #555; line-height: 2; }
        .cover-page .details .label { font-weight: bold; }
        .text-success { color: #2e7d32; }
        .text-danger { color: #c62828; }
        .text-warning { color: #e65100; }
        .text-primary { color: #1a237e; }
        .text-muted { color: #757575; }
        .summary-grid { display: flex; flex-wrap: wrap; gap: 10px; justify-content: center; margin: 15px 0; }
        .summary-item { text-align: center; padding: 6px 12px; background: #f5f5f5; border-radius: 6px; min-width: 80px; }
        .summary-item .number { font-size: 16px; font-weight: bold; }
        .summary-item .label { font-size: 8px; color: #666; }
    </style>
</head>
<body>
    <!-- Cover Page -->
    <div class="cover-page">
        <div style="font-size:48px; margin-bottom:15px;">🏠</div>
        <h1>Bulk Payment Receipts</h1>
        <h2>{{ date('F Y') }}</h2>
        <div class="details">
            <div><span class="label">Generated on:</span> {{ $generated_at }}</div>
            <div><span class="label">Generated By:</span> {{ $user->name }} ({{ $user->role }})</div>
            <div><span class="label">Total Receipts:</span> {{ count($payments) }}</div>
            @php
                $totalRent = $payments->sum('rent_amount');
                $totalCollected = $payments->sum('cash_paid_amount') + $payments->sum('upi_paid_amount');
                $totalBalance = $payments->sum('balance_amount');
                $paidCount = $payments->where('status', 'PAID')->count();
                $pendingCount = $payments->where('status', 'PENDING')->count();
                $partialCount = $payments->where('status', 'PARTIAL')->count();
            @endphp
            <div style="margin-top:15px;">
                <div class="summary-grid">
                    <div class="summary-item">
                        <div class="number text-success">{{ $paidCount }}</div>
                        <div class="label">✅ Paid</div>
                    </div>
                    <div class="summary-item">
                        <div class="number text-danger">{{ $pendingCount }}</div>
                        <div class="label">⏳ Pending</div>
                    </div>
                    <div class="summary-item">
                        <div class="number text-warning">{{ $partialCount }}</div>
                        <div class="label">🟡 Partial</div>
                    </div>
                    <div class="summary-item">
                        <div class="number text-primary">₹{{ number_format($totalRent, 0) }}</div>
                        <div class="label">Total Rent</div>
                    </div>
                    <div class="summary-item">
                        <div class="number text-success">₹{{ number_format($totalCollected, 0) }}</div>
                        <div class="label">Collected</div>
                    </div>
                    <div class="summary-item">
                        <div class="number text-danger">₹{{ number_format($totalBalance, 0) }}</div>
                        <div class="label">Balance</div>
                    </div>
                </div>
            </div>
        </div>
        <div style="margin-top:30px; font-size:9px; color:#999;">
            This document contains {{ count($payments) }} payment receipts
        </div>
    </div>

    <div class="page-break"></div>

    <!-- Individual Receipts -->
    @foreach($payments as $index => $payment)
        <div class="receipt-box" style="{{ $index > 0 ? 'margin-top:20px;' : '' }}">
            <div class="receipt-header">
                <div class="logo">🏠 {{ $payment->resident->hostel->hostel_name ?? 'Hostel' }}</div>
                <div class="receipt-no">Receipt #{{ $payment->receipt_no }}</div>
            </div>

            <div style="display:flex; justify-content:space-between; font-size:8px; color:#666; margin-bottom:5px;">
                <span>Date: {{ $payment->payment_date }}</span>
                <span>Status: <span class="status-badge status-{{ strtolower($payment->status) }}">{{ $payment->status }}</span></span>
            </div>

            <div class="section-title">Resident Details</div>
            <div class="row">
                <span class="label">Name</span>
                <span class="value">{{ $payment->resident->name ?? 'N/A' }}</span>
            </div>
            <div class="row">
                <span class="label">Room</span>
                <span class="value">#{{ $payment->resident->room->room_no ?? 'N/A' }} | Bed: {{ $payment->resident->bed_number ?? 'N/A' }}</span>
            </div>
            <div class="row">
                <span class="label">Month</span>
                <span class="value">{{ date('F', mktime(0, 0, 0, $payment->month, 1)) }} {{ $payment->year }}</span>
            </div>

            <div class="section-title" style="margin-top:6px;">Amount Details</div>
            <div class="row">
                <span class="label">Rent</span>
                <span class="value">₹{{ number_format($payment->rent_amount, 2) }}</span>
            </div>
            @if($payment->discount_amount > 0)
            <div class="row" style="color:#2e7d32;">
                <span class="label">Discount</span>
                <span class="value">-₹{{ number_format($payment->discount_amount, 2) }}</span>
            </div>
            @endif
            @if($payment->fine_amount > 0)
            <div class="row" style="color:#c62828;">
                <span class="label">Fine</span>
                <span class="value">+₹{{ number_format($payment->fine_amount, 2) }}</span>
            </div>
            @endif
            <div class="row">
                <span class="label">Cash</span>
                <span class="value">₹{{ number_format($payment->cash_paid_amount, 2) }}</span>
            </div>
            <div class="row">
                <span class="label">UPI</span>
                <span class="value">₹{{ number_format($payment->upi_paid_amount, 2) }}</span>
            </div>

            <div class="total-row">
                <span class="label">Total Paid</span>
                <span class="value">₹{{ number_format($payment->cash_paid_amount + $payment->upi_paid_amount, 2) }}</span>
            </div>
            <div class="total-row" style="background:{{ $payment->balance_amount > 0 ? '#ffebee' : '#e8f5e9' }};">
                <span class="label">Balance</span>
                <span class="value {{ $payment->balance_amount > 0 ? 'text-danger' : 'text-success' }}">
                    ₹{{ number_format($payment->balance_amount, 2) }}
                </span>
            </div>

            @if($payment->transaction_id)
            <div style="font-size:8px; color:#666; margin-top:4px;">
                Txn ID: {{ $payment->transaction_id }}
            </div>
            @endif

            <div class="footer">
                Generated on: {{ $generated_at }} | {{ $payment->resident->hostel->hostel_name ?? '' }}
            </div>
        </div>
        @if(($index + 1) % 3 == 0 && !$loop->last)
            <div class="page-break"></div>
        @endif
    @endforeach
</body>
</html>
