<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; padding: 15px; }
        .header { text-align: center; border-bottom: 3px solid #f57c00; padding-bottom: 12px; margin-bottom: 15px; }
        .header h1 { font-size: 18px; color: #f57c00; }
        .header p { font-size: 10px; color: #666; margin-top: 3px; }
        .report-info { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 9px; background: #fff3e0; padding: 6px 10px; border-radius: 4px; flex-wrap: wrap; }
        .report-info .label { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; font-size: 8.5px; }
        table th { background: #f57c00; color: white; padding: 5px 3px; text-align: left; font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.3px; }
        table td { padding: 3px; border-bottom: 1px solid #e0e0e0; }
        table tr:nth-child(even) { background: #f8f9fa; }
        .badge { padding: 1px 6px; border-radius: 8px; font-size: 7px; font-weight: bold; display: inline-block; }
        .badge-paid { background: #c8e6c9; color: #2e7d32; }
        .badge-pending { background: #ffcdd2; color: #c62828; }
        .badge-partial { background: #ffe0b2; color: #e65100; }
        .badge-no-payment { background: #e0e0e0; color: #757575; }
        .footer { margin-top: 15px; padding-top: 8px; border-top: 1px solid #e0e0e0; text-align: center; font-size: 8px; color: #999; }
        .summary-box { margin-top: 12px; padding: 8px 12px; background: #fff3e0; border-radius: 4px; border-left: 4px solid #f57c00; }
        .summary-box h3 { font-size: 11px; color: #f57c00; margin-bottom: 6px; }
        .summary-grid { display: flex; flex-wrap: wrap; gap: 10px; }
        .summary-item { font-size: 9px; }
        .summary-item .number { font-weight: bold; font-size: 11px; }
        .summary-item .label { color: #666; }
        .text-success { color: #2e7d32; }
        .text-danger { color: #c62828; }
        .text-warning { color: #e65100; }
        .text-primary { color: #1a237e; }
        .text-muted { color: #757575; }
        .page-break { page-break-after: always; }
        .section-title { font-size: 12px; font-weight: bold; color: #f57c00; margin: 10px 0 8px 0; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🏢 {{ $title }}</h1>
        <p>Generated on: {{ $generated_at }}</p>
    </div>

    <div class="report-info">
        <div><span class="label">Hostel:</span> {{ $hostel->hostel_name }} ({{ $hostel->hostel_code }})</div>
        <div><span class="label">Total Residents:</span> {{ $summary['total_residents'] }}</div>
        <div><span class="label">Total Payments:</span> {{ $summary['total_payments'] }}</div>
        <div><span class="label">Generated By:</span> {{ $user->name }}</div>
    </div>

    <div class="section-title">📋 Resident-wise Payment Summary</div>
    <table>
        <thead>
            <tr>
                <th width="30">S.No</th>
                <th width="100">Resident Name</th>
                <th width="45">Room</th>
                <th width="40">Bed</th>
                <th width="50">Rent (₹)</th>
                <th width="50">Paid (₹)</th>
                <th width="50">Balance (₹)</th>
                <th width="40">Count</th>
                <th width="60">Status</th>
            </tr>
        </thead>
        <tbody>
            @php $serialNo = 1; @endphp
            @foreach($residentSummaries as $item)
                @php
                    $resident = $item['resident'];
                    $roomNo = $resident->room ? $resident->room->room_no : 'N/A';
                    $bedNo = $resident->bed_no ?? 'N/A';
                    $status = $item['status'];
                    $statusClass = strtolower(str_replace(' ', '-', $status));
                @endphp
                <tr>
                    <td>{{ $serialNo++ }}</td>
                    <td>{{ $resident->name }}</td>
                    <td>#{{ $roomNo }}</td>
                    <td>{{ $bedNo }}</td>
                    <td>{{ number_format($resident->rent_amount ?? 0, 2) }}</td>
                    <td>{{ number_format($item['total_paid'], 2) }}</td>
                    <td>{{ number_format($item['total_balance'], 2) }}</td>
                    <td>{{ $item['count'] }}</td>
                    <td><span class="badge badge-{{ $statusClass }}">{{ $status }}</span></td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title" style="margin-top:15px;">📄 Detailed Payment Transactions</div>
    @if(count($payments) > 0)
        <table>
            <thead>
                <tr>
                    <th>Receipt</th>
                    <th>Resident</th>
                    <th>Room</th>
                    <th>Month</th>
                    <th>Year</th>
                    <th>Rent (₹)</th>
                    <th>Disc (₹)</th>
                    <th>Fine (₹)</th>
                    <th>Cash (₹)</th>
                    <th>UPI (₹)</th>
                    <th>Paid (₹)</th>
                    <th>Balance (₹)</th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($payments as $payment)
                    @php
                        $monthName = date('F', mktime(0, 0, 0, $payment->month, 1));
                        $totalPaid = $payment->cash_paid_amount + $payment->upi_paid_amount;
                        $statusClass = strtolower($payment->status);
                    @endphp
                    <tr>
                        <td>{{ $payment->receipt_no }}</td>
                        <td>{{ $payment->resident->name ?? 'N/A' }}</td>
                        <td>#{{ $payment->resident->room->room_no ?? 'N/A' }}</td>
                        <td>{{ $monthName }}</td>
                        <td>{{ $payment->year }}</td>
                        <td>{{ number_format($payment->rent_amount, 2) }}</td>
                        <td>{{ number_format($payment->discount_amount, 2) }}</td>
                        <td>{{ number_format($payment->fine_amount, 2) }}</td>
                        <td>{{ number_format($payment->cash_paid_amount, 2) }}</td>
                        <td>{{ number_format($payment->upi_paid_amount, 2) }}</td>
                        <td><strong>{{ number_format($totalPaid, 2) }}</strong></td>
                        <td>{{ number_format($payment->balance_amount, 2) }}</td>
                        <td><span class="badge badge-{{ $statusClass }}">{{ $payment->status }}</span></td>
                        <td>{{ $payment->payment_date }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align:center; padding:15px; background:#f5f5f5; border-radius:4px;">
            <p style="color:#666; font-size:10px;">No payment records found</p>
        </div>
    @endif

    <div class="summary-box">
        <h3>📊 Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="number text-success">{{ $summary['paid'] }}</div>
                <div class="label">✅ Paid</div>
            </div>
            <div class="summary-item">
                <div class="number text-danger">{{ $summary['pending'] }}</div>
                <div class="label">⏳ Pending</div>
            </div>
            <div class="summary-item">
                <div class="number text-warning">{{ $summary['partial'] }}</div>
                <div class="label">🟡 Partial</div>
            </div>
            <div class="summary-item">
                <div class="number text-primary">₹{{ number_format($summary['total_rent'], 2) }}</div>
                <div class="label">Total Rent</div>
            </div>
            <div class="summary-item">
                <div class="number text-success">₹{{ number_format($summary['total_collected'], 2) }}</div>
                <div class="label">Total Collected</div>
            </div>
            <div class="summary-item">
                <div class="number text-danger">₹{{ number_format($summary['total_balance'], 2) }}</div>
                <div class="label">Total Balance</div>
            </div>
            <div class="summary-item">
                <div class="number text-primary">{{ number_format(($summary['total_rent'] > 0 ? ($summary['total_collected'] / $summary['total_rent']) * 100 : 0), 1) }}%</div>
                <div class="label">Collection %</div>
            </div>
        </div>
    </div>

    <div class="footer">
        Generated by: {{ $user->name }} ({{ $user->role }}) | {{ $generated_at }}
    </div>
</body>
</html>
