<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; padding: 15px; }
        .header { text-align: center; border-bottom: 3px solid #c62828; padding-bottom: 12px; margin-bottom: 15px; }
        .header h1 { font-size: 18px; color: #c62828; }
        .header p { font-size: 10px; color: #666; margin-top: 3px; }
        .report-info { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 9px; background: #ffebee; padding: 6px 10px; border-radius: 4px; flex-wrap: wrap; }
        .report-info .label { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; font-size: 8.5px; }
        table th { background: #c62828; color: white; padding: 5px 3px; text-align: left; font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.3px; }
        table td { padding: 3px; border-bottom: 1px solid #e0e0e0; }
        table tr:nth-child(even) { background: #f8f9fa; }
        .badge { padding: 1px 6px; border-radius: 8px; font-size: 7px; font-weight: bold; display: inline-block; }
        .badge-pending { background: #ffcdd2; color: #c62828; }
        .badge-partial { background: #ffe0b2; color: #e65100; }
        .badge-no-payment { background: #e0e0e0; color: #757575; }
        .footer { margin-top: 15px; padding-top: 8px; border-top: 1px solid #e0e0e0; text-align: center; font-size: 8px; color: #999; }
        .summary-box { margin-top: 12px; padding: 8px 12px; background: #ffebee; border-radius: 4px; border-left: 4px solid #c62828; }
        .summary-box h3 { font-size: 11px; color: #c62828; margin-bottom: 6px; }
        .summary-grid { display: flex; flex-wrap: wrap; gap: 10px; }
        .summary-item { font-size: 9px; }
        .summary-item .number { font-weight: bold; font-size: 11px; }
        .summary-item .label { color: #666; }
        .text-danger { color: #c62828; }
        .text-warning { color: #e65100; }
        .text-muted { color: #757575; }
        .text-primary { color: #1a237e; }
        .text-success { color: #2e7d32; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📅 {{ $title }}</h1>
        <p>Generated on: {{ $generated_at }}</p>
    </div>

    <div class="report-info">
        <div><span class="label">Month:</span> {{ $month }} {{ $year }}</div>
        <div><span class="label">Hostel:</span> {{ $hostel }}</div>
        <div><span class="label">Unpaid Residents:</span> {{ $totalUnpaid }}</div>
        <div><span class="label">Total Due:</span> ₹{{ number_format($totalDue, 2) }}</div>
        <div><span class="label">Generated By:</span> {{ $user->name }}</div>
    </div>

    @if($totalUnpaid > 0)
        <table>
            <thead>
                <tr>
                    <th width="30">S.No</th>
                    <th width="100">Resident Name</th>
                    <th width="80">Hostel</th>
                    <th width="45">Room</th>
                    <th width="40">Bed</th>
                    <th width="60">Phone</th>
                    <th width="50">Rent (₹)</th>
                    <th width="50">Due (₹)</th>
                    <th width="60">Status</th>
                </tr>
            </thead>
            <tbody>
                @php $serialNo = 1; @endphp
                @foreach($unpaidResidents as $item)
                    @php
                        $resident = $item['resident'];
                        $roomNo = $resident->room ? $resident->room->room_no : 'N/A';
                        $bedNo = $resident->bed_no ?? 'N/A';
                        $status = $item['status'];
                        $statusClass = strtolower(str_replace(' ', '-', $status));
                    @endphp
                    <tr>
                        <td>{{ $serialNo++ }}</td>
                        <td><strong>{{ $resident->name }}</strong></td>
                        <td>{{ $resident->hostel->hostel_name ?? 'N/A' }}</td>
                        <td>#{{ $roomNo }}</td>
                        <td>{{ $bedNo }}</td>
                        <td>{{ $resident->phone ?? '' }}</td>
                        <td>{{ number_format($resident->rent_amount ?? 0, 2) }}</td>
                        <td><strong>₹{{ number_format($item['due_amount'], 2) }}</strong></td>
                        <td><span class="badge badge-{{ $statusClass }}">{{ $status }}</span></td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="summary-box">
            <h3>📊 Summary</h3>
            <div class="summary-grid">
                <div class="summary-item">
                    <div class="number text-danger">{{ $totalUnpaid }}</div>
                    <div class="label">Total Unpaid</div>
                </div>
                <div class="summary-item">
                    <div class="number text-danger">₹{{ number_format($totalDue, 2) }}</div>
                    <div class="label">Total Due</div>
                </div>
                <div class="summary-item">
                    <div class="number text-primary">{{ number_format($totalUnpaid > 0 ? ($totalDue / $totalUnpaid) : 0, 2) }}</div>
                    <div class="label">Avg Due per Resident</div>
                </div>
            </div>
        </div>
    @else
        <div style="text-align:center; padding:30px; background:#e8f5e9; border-radius:8px;">
            <h2 style="color:#2e7d32;">✅ All Residents Have Paid</h2>
            <p style="color:#666; font-size:11px;">No unpaid residents found for {{ $month }} {{ $year }}</p>
        </div>
    @endif

    <div class="footer">
        Generated by: {{ $user->name }} ({{ $user->role }}) | {{ $generated_at }}
    </div>
</body>
</html>
