<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; padding: 15px; }
        .header { text-align: center; border-bottom: 3px solid #1a237e; padding-bottom: 12px; margin-bottom: 15px; }
        .header h1 { font-size: 18px; color: #1a237e; }
        .header p { font-size: 10px; color: #666; margin-top: 3px; }
        .report-info { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 9px; background: #f5f5f5; padding: 6px 10px; border-radius: 4px; flex-wrap: wrap; }
        .report-info .label { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; font-size: 8.5px; }
        table th { background: #1a237e; color: white; padding: 5px 3px; text-align: left; font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.3px; }
        table td { padding: 3px; border-bottom: 1px solid #e0e0e0; }
        table tr:nth-child(even) { background: #f8f9fa; }
        .footer { margin-top: 15px; padding-top: 8px; border-top: 1px solid #e0e0e0; text-align: center; font-size: 8px; color: #999; }
        .summary-box { margin-top: 12px; padding: 8px 12px; background: #e8eaf6; border-radius: 4px; border-left: 4px solid #1a237e; }
        .summary-box h3 { font-size: 11px; color: #1a237e; margin-bottom: 6px; }
        .summary-grid { display: flex; flex-wrap: wrap; gap: 10px; }
        .summary-item { font-size: 9px; }
        .summary-item .number { font-weight: bold; font-size: 11px; }
        .summary-item .label { color: #666; }
        .text-success { color: #2e7d32; }
        .text-danger { color: #c62828; }
        .text-warning { color: #e65100; }
        .text-primary { color: #1a237e; }
        .text-muted { color: #757575; }
        .text-gold { color: #f57c00; }
        .grand-total { background: #e8eaf6; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 {{ $title }}</h1>
        <p>Generated on: {{ $generated_at }}</p>
    </div>

    <div class="report-info">
        <div><span class="label">Total Hostels:</span> {{ count($hostelSummaries) }}</div>
        <div><span class="label">Total Residents:</span> {{ $grandTotal['residents'] }}</div>
        <div><span class="label">Total Payments:</span> {{ $grandTotal['payments'] }}</div>
        <div><span class="label">Generated By:</span> {{ $user->name }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Hostel</th>
                <th>Residents</th>
                <th>Payments</th>
                <th>Total Rent (₹)</th>
                <th>Collected (₹)</th>
                <th>Balance (₹)</th>
                <th>✅ Paid</th>
                <th>⏳ Pending</th>
                <th>🟡 Partial</th>
                <th>Collection %</th>
            </tr>
        </thead>
        <tbody>
            @php $serialNo = 1; @endphp
            @foreach($hostelSummaries as $item)
                @php
                    $collectionPercent = $item['total_rent'] > 0 ? round(($item['total_collected'] / $item['total_rent']) * 100, 1) : 0;
                @endphp
                <tr>
                    <td>{{ $serialNo++ }}</td>
                    <td><strong>{{ $item['hostel']->hostel_name }}</strong></td>
                    <td>{{ $item['residents'] }}</td>
                    <td>{{ $item['payments_count'] }}</td>
                    <td>{{ number_format($item['total_rent'], 2) }}</td>
                    <td><strong>{{ number_format($item['total_collected'], 2) }}</strong></td>
                    <td>{{ number_format($item['total_balance'], 2) }}</td>
                    <td><span style="color:#2e7d32;">{{ $item['paid'] }}</span></td>
                    <td><span style="color:#c62828;">{{ $item['pending'] }}</span></td>
                    <td><span style="color:#e65100;">{{ $item['partial'] }}</span></td>
                    <td><strong>{{ $collectionPercent }}%</strong></td>
                </tr>
            @endforeach
            <tr class="grand-total">
                <td colspan="2"><strong>GRAND TOTAL</strong></td>
                <td><strong>{{ $grandTotal['residents'] }}</strong></td>
                <td><strong>{{ $grandTotal['payments'] }}</strong></td>
                <td><strong>{{ number_format($grandTotal['rent'], 2) }}</strong></td>
                <td><strong>{{ number_format($grandTotal['collected'], 2) }}</strong></td>
                <td><strong>{{ number_format($grandTotal['balance'], 2) }}</strong></td>
                <td><strong>{{ $grandTotal['paid'] }}</strong></td>
                <td><strong>{{ $grandTotal['pending'] }}</strong></td>
                <td><strong>{{ $grandTotal['partial'] }}</strong></td>
                <td><strong>{{ number_format(($grandTotal['rent'] > 0 ? ($grandTotal['collected'] / $grandTotal['rent']) * 100 : 0), 1) }}%</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="summary-box">
        <h3>📊 Overall Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="number text-success">{{ $grandTotal['paid'] }}</div>
                <div class="label">✅ Paid</div>
            </div>
            <div class="summary-item">
                <div class="number text-danger">{{ $grandTotal['pending'] }}</div>
                <div class="label">⏳ Pending</div>
            </div>
            <div class="summary-item">
                <div class="number text-warning">{{ $grandTotal['partial'] }}</div>
                <div class="label">🟡 Partial</div>
            </div>
            <div class="summary-item">
                <div class="number text-primary">₹{{ number_format($grandTotal['rent'], 2) }}</div>
                <div class="label">Total Rent</div>
            </div>
            <div class="summary-item">
                <div class="number text-success">₹{{ number_format($grandTotal['collected'], 2) }}</div>
                <div class="label">Total Collected</div>
            </div>
            <div class="summary-item">
                <div class="number text-danger">₹{{ number_format($grandTotal['balance'], 2) }}</div>
                <div class="label">Total Balance</div>
            </div>
            <div class="summary-item">
                <div class="number text-gold">{{ number_format(($grandTotal['rent'] > 0 ? ($grandTotal['collected'] / $grandTotal['rent']) * 100 : 0), 1) }}%</div>
                <div class="label">Collection %</div>
            </div>
            <div class="summary-item">
                <div class="number text-primary">{{ $grandTotal['residents'] }}</div>
                <div class="label">Total Residents</div>
            </div>
            <div class="summary-item">
                <div class="number text-primary">{{ $grandTotal['payments'] }}</div>
                <div class="label">Total Payments</div>
            </div>
        </div>
    </div>

    <div class="footer">
        Generated by: {{ $user->name }} ({{ $user->role }}) | {{ $generated_at }}
    </div>
</body>
</html>
