<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; padding: 15px; }
        .header { text-align: center; border-bottom: 3px solid #1a237e; padding-bottom: 12px; margin-bottom: 15px; }
        .header h1 { font-size: 18px; color: #1a237e; }
        .header p { font-size: 10px; color: #666; margin-top: 3px; }
        .report-info { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 9px; background: #f5f5f5; padding: 6px 10px; border-radius: 4px; }
        .report-info .label { font-weight: bold; }
        table { width: 100%; border-collapse: collapse; font-size: 8.5px; }
        table th { background: #1a237e; color: white; padding: 5px 3px; text-align: left; font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.3px; }
        table td { padding: 3px; border-bottom: 1px solid #e0e0e0; }
        table tr:nth-child(even) { background: #f8f9fa; }
        .badge { padding: 1px 6px; border-radius: 8px; font-size: 7px; font-weight: bold; display: inline-block; }
        .badge-paid { background: #c8e6c9; color: #2e7d32; }
        .badge-pending { background: #ffcdd2; color: #c62828; }
        .badge-partial { background: #ffe0b2; color: #e65100; }
        .badge-no-payment { background: #e0e0e0; color: #757575; }
        .footer { margin-top: 15px; padding-top: 8px; border-top: 1px solid #e0e0e0; text-align: center; font-size: 8px; color: #999; }
        .summary-box { margin-top: 12px; padding: 8px 12px; background: #f5f5f5; border-radius: 4px; }
        .summary-box h3 { font-size: 11px; color: #1a237e; margin-bottom: 6px; }
        .summary-grid { display: flex; flex-wrap: wrap; gap: 10px; }
        .summary-item { font-size: 9px; }
        .summary-item .number { font-weight: bold; font-size: 11px; }
        .summary-item .label { color: #666; }
        .text-success { color: #2e7d32; }
        .text-danger { color: #c62828; }
        .text-warning { color: #e65100; }
        .text-muted { color: #757575; }
        .text-primary { color: #1a237e; }
        .status-paid { color: #2e7d32; font-weight: bold; }
        .status-pending { color: #c62828; font-weight: bold; }
        .status-partial { color: #e65100; font-weight: bold; }
        .status-no-payment { color: #757575; font-weight: bold; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated on: {{ $generated_at }}</p>
    </div>

    <div class="report-info">
        <div><span class="label">Month:</span> {{ $month }} {{ $year }}</div>
        <div><span class="label">Hostel:</span> {{ $hostel }}</div>
        <div><span class="label">Total Residents:</span> {{ $residents->count() }}</div>
        <div><span class="label">Generated By:</span> {{ $user->name }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="30">S.No</th>
                <th width="80">Hostel</th>
                <th width="45">Room</th>
                <th width="40">Bed</th>
                <th width="100">Resident Name</th>
                <th width="60">Phone</th>
                <th width="50">Rent (₹)</th>
                <th width="60">Status</th>
                <th width="70">Receipt No</th>
                <th width="50">Paid (₹)</th>
                <th width="50">Balance (₹)</th>
            </tr>
        </thead>
        <tbody>
            @php $serialNo = 1; @endphp
            @foreach($residents as $resident)
                @php
                    $payment = $payments->get($resident->id);
                    $roomNo = $resident->room ? $resident->room->room_no : 'N/A';
                    $bedNo = $resident->bed_number ?? 'N/A';
                    $rent = $resident->rent_amount ?? 0;
                    $paid = $payment ? ($payment->cash_paid_amount + $payment->upi_paid_amount) : 0;
                    $balance = $payment ? $payment->balance_amount : $rent;
                    $status = $payment ? $payment->status : 'NO PAYMENT';
                    $statusClass = strtolower(str_replace(' ', '-', $status));
                @endphp
                <tr>
                    <td>{{ $serialNo++ }}</td>
                    <td>{{ $resident->hostel->hostel_name ?? 'N/A' }}</td>
                    <td>#{{ $roomNo }}</td>
                    <td>{{ $bedNo }}</td>
                    <td>{{ $resident->name }}</td>
                    <td>{{ $resident->phone ?? '' }}</td>
                    <td>{{ number_format($rent, 2) }}</td>
                    <td><span class="badge badge-{{ $statusClass }}">{{ $status }}</span></td>
                    <td>{{ $payment ? $payment->receipt_no : '' }}</td>
                    <td>{{ number_format($paid, 2) }}</td>
                    <td>{{ number_format($balance, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @php
        $totalPaid = 0;
        $totalBalance = 0;
        $totalRent = 0;
        $paidCount = 0;
        $pendingCount = 0;
        $partialCount = 0;
        $noPaymentCount = 0;

        foreach($residents as $resident) {
            $payment = $payments->get($resident->id);
            $totalRent += $resident->rent_amount ?? 0;
            if ($payment) {
                $totalPaid += $payment->cash_paid_amount + $payment->upi_paid_amount;
                $totalBalance += $payment->balance_amount;
                if ($payment->status === 'PAID') $paidCount++;
                elseif ($payment->status === 'PENDING') $pendingCount++;
                elseif ($payment->status === 'PARTIAL') $partialCount++;
            } else {
                $noPaymentCount++;
                $totalBalance += $resident->rent_amount ?? 0;
            }
        }
    @endphp

    <div class="summary-box">
        <h3>📊 Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <div class="number text-success">{{ $paidCount }}</div>
                <div class="label">✅ Paid</div>
            </div>
            <div class="summary-item">
                <div class="number text-danger">{{ $pendingCount }}</div>
                <div class="label">⏳ Pending</div>
            </div>
            <div class="summary-item">
                <div class="number text-warning">{{ $partialCount }}</div>
                <div class="label">🟡 Partial</div>
            </div>
            <div class="summary-item">
                <div class="number text-muted">{{ $noPaymentCount }}</div>
                <div class="label">⬜ No Payment</div>
            </div>
            <div class="summary-item">
                <div class="number text-primary">₹{{ number_format($totalRent, 2) }}</div>
                <div class="label">Total Rent</div>
            </div>
            <div class="summary-item">
                <div class="number text-success">₹{{ number_format($totalPaid, 2) }}</div>
                <div class="label">Total Paid</div>
            </div>
            <div class="summary-item">
                <div class="number text-danger">₹{{ number_format($totalBalance, 2) }}</div>
                <div class="label">Total Balance</div>
            </div>
            <div class="summary-item">
                <div class="number text-primary">{{ number_format(($totalRent > 0 ? ($totalPaid / $totalRent) * 100 : 0), 1) }}%</div>
                <div class="label">Collection %</div>
            </div>
        </div>
    </div>

    <div class="footer">
        Generated by: {{ $user->name }} ({{ $user->role }}) | {{ $generated_at }}
    </div>
</body>
</html>
